name: "My PRT workflow"
on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  create-issue:
    name: Create tracking issue
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - name: print fork repo's name
        if: github.event.pull_request.head.repo.owner.login != 'hashtagchris'
        run: echo ${{ github.event.pull_request.head.repo.owner.login }}
        
      - run: echo "$GITHUB_ACTOR triggered $GITHUB_EVENT_NAME"
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_SHA
      - run: cat $GITHUB_EVENT_PATH
      - name: Echo a repository secret
        run: echo ${{ secrets.TEST_REPO_SECRET }} | rev
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        with:
          script: |
              await github.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `${context.eventName} event triggered by ${context.actor}`,
                body: `ref: ${context.ref}\nsha: ${context.sha}\nactor: ${context.actor}`,
              })  
