name: print secrets
on:
  push:
  pull_request:
  pull_request_target:
  issues:
  issue_comment:
  workflow_dispatch:
  create:
  deployment:
  deployment_status:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo $SECRETS
        env:
          SECRETS: ${{ toJson(secrets) }}
